USE Biblioteca;

-- Create tables
CREATE TABLE IF NOT EXISTS Autores (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    nacionalidad VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Libros (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    genero VARCHAR(255) NOT NULL,
    año_publicacion INT NOT NULL,
    Autor_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY Autor_ID REFERENCES Autores(id)
);